version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://nestjs:nestjs@postgres:5432/nestjs_db
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:
