version: '3.8'

services:
  # redis:
  #   image: redis:7
  #   container_name: redis-dev
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

  # postgres:
  #   image: postgres:15
  #   container_name: postgres-dev
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: nestjs
  #     POSTGRES_PASSWORD: nestjs
  #     POSTGRES_DB: nestjs_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: nest-app
    ports:
      - '3002:3002'
    # depends_on:
    #   - redis
    #   # - postgres
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}

    restart: unless-stopped

  prisma-studio:
    image: node:18-alpine
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npx prisma generate && npx prisma studio --port 5555"
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    # depends_on:
    #   - postgres


# volumes:
#   redis-data:
  # postgres-data:
