version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped

volumes:
  redis-data:
